/*	START NEW ARIX SCCS HEADER			*/
/*							*/
/*	@(#) t_getstate.c: version 25.1 created on 12/2/91 at 20:17:52	*/
/*							*/
/*	Copyright (c) 1990 by Arix Corporation		*/
/*	All Rights Reserved				*/
/*							*/
#ident	"@(#)t_getstate.c	25.1	12/2/91 Copyright (c) 1990 by Arix Corporation"
/*							*/
/*	END NEW ARIX SCCS HEADER			*/
/*							*/
/*	Copyright (c) 1984 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

/*	ATT: #ident	"libnsl:nsl/t_getstate.c	1.4.1.2"*/

#ident	"@(#)lib/nsl:t_getstate.c	25.1"

#include "sys/errno.h"
#include "sys/types.h"
#include "sys/stream.h"
#include "sys/stropts.h"
#include "sys/tihdr.h"
#include "sys/timod.h"
#include "sys/tiuser.h"
#include "stdio.h"
#include "sys/signal.h"
#include "_import.h"


extern int t_errno;
extern int errno;
extern struct _ti_user *_t_checkfd();

t_getstate(fd)
int fd;
{
	register struct _ti_user *tiptr;

	if ((tiptr = _t_checkfd(fd)) == NULL)
		return(-1);

	switch (tiptr->ti_state) {

	case T_UNBND:
	case T_IDLE:
	case T_INCON:
	case T_OUTCON:
	case T_DATAXFER:
	case T_INREL:
	case T_OUTREL:
		return(tiptr->ti_state);
	case T_FAKE:
	case T_HACK:
	/* T_HACK needed to maintain compatibility!!!
	 * DO NOT REMOVE UNTIL _spec FILE REORDERED!!!!
  	 *
	 * It's purpose is to keep the size of the data
	 * generated by the compilation of the switch 
 	 * statement the same as before (range of 12).  If it is removed
	 * or changed the locations of the imported symbols
	 * will change, breaking compatibility.
	 */
	default:
		t_errno = TSTATECHNG;
		return(-1);
	}
}
