#	START NEW ARIX SCCS HEADER
#
#	@(#) vt0.mk: version 25.1 created on 12/2/91 at 20:13:49
#
#	Copyright (c) 1990 by Arix Corporation
#	All Rights Reserved
#
#	@(#)vt0.mk	25.1	12/2/91 Copyright (c) 1990 by Arix Corporation
#
#	END NEW ARIX SCCS HEADER
#
#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#	ATT: ident	"libplot:vt0/vt0.mk	1.7"
#ident	"@(#)libplot/vt0:vt0.mk	25.1"

#	Makefile for vt0 library

IROOT =
include $(IROOT)/macdefs

DIR = $(ROOT)/usr/$(SGS)lib
USRLIB = $(DIR)

INC = $(INCRT)

STRIP = strip

SIZE = size

LIST = lp

#top#
# Generated by makefile 1.47

MAKEFILE = vt0.mk


LIBRARY = libvt0.a

OBJECTS =  arc.o box.o circle.o close.o dot.o erase.o frame.o label.o line.o \
	linmod.o move.o open.o point.o space.o subr.o

SOURCES =  arc.c box.c circle.c close.c dot.c erase.c frame.c label.c line.c \
	linmod.c move.c open.c point.c space.c subr.c

ALL:		$(LIBRARY)

$(LIBRARY):	$(LIBRARY)(subr.o) $(LIBRARY)(space.o) \
		$(LIBRARY)(point.o) $(LIBRARY)(open.o) $(LIBRARY)(move.o) \
		$(LIBRARY)(linmod.o) $(LIBRARY)(line.o)	\
		$(LIBRARY)(label.o) $(LIBRARY)(frame.o)	\
		$(LIBRARY)(erase.o) $(LIBRARY)(dot.o) $(LIBRARY)(close.o) \
		$(LIBRARY)(circle.o) $(LIBRARY)(box.o) $(LIBRARY)(arc.o) 


$(LIBRARY)(arc.o): 

$(LIBRARY)(box.o): 

$(LIBRARY)(circle.o):	 

$(LIBRARY)(close.o):	 

$(LIBRARY)(dot.o): 

$(LIBRARY)(erase.o):	 

$(LIBRARY)(frame.o):	 

$(LIBRARY)(label.o):	 

$(LIBRARY)(line.o): 

$(LIBRARY)(linmod.o):	 

$(LIBRARY)(move.o): 

$(LIBRARY)(open.o): 

$(LIBRARY)(point.o):	 

$(LIBRARY)(space.o):	 

$(LIBRARY)(subr.o): 

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(LIBRARY) tags greplist

newmakefile:
	makefile -m -f $(MAKEFILE) -L $(LIBRARY)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) $(LIBRARY) $(USRLIB)/$(LIBRARY)
	$(AR) ts $(USRLIB)/$(LIBRARY)
	chmod 644 $(USRLIB)/$(LIBRARY)
	chgrp bin $(USRLIB)/$(LIBRARY)
	chown bin $(USRLIB)/$(LIBRARY)

size: ALL
	$(SIZE) $(LIBRARY)

strip: ALL

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(USRLIB) | tr ' ' '\012' | sort

product:
	@echo $(LIBRARY)  |  tr ' ' '\012'  | \
	sed 's;^;$(USRLIB)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(LIBRARY)

listing:
	pr -n $(MAKEFILE) $(SOURCES) | $(LIST)

listmk:
	pr -n $(MAKEFILE) | $(LIST)
ctags:	
	ctags	$(SOURCES)
	echo 'grep $$* \\' > greplist
	for i in $(SOURCES)	;\
	do echo "$$i \\"	;\
	done >> greplist
	echo /dev/null >> greplist
	chmod +x greplist
