 #include <stdio.h>
 #ifdef DYNAMIC
	extern FILE _iob[];
	extern unsigned char _smbuf[];
	FILE _iob[_NFILE] = {
		{ 0, NULL, NULL, _IOREAD|_IOIOB, 0, NULL, stdout, NULL },
		{ 0, NULL, NULL, _IOWRT|_IOIOB, 1, NULL, stderr, stdin },
		{ 0, _smbuf, _smbuf, _IOWRT|_IONBF|_IOIOB, 2,
		  &_smbuf[_SBFSIZ], NULL, stdout }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[4], NULL }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[5], &_iob[3] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[6], &_iob[4] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[7], &_iob[5] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[8], &_iob[6] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[9], &_iob[7] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[10], &_iob[8] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[11], &_iob[9] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[12], &_iob[10] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[13], &_iob[11] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[14], &_iob[12] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[15], &_iob[13] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[16], &_iob[14] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[17], &_iob[15] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[18], &_iob[16] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[19], &_iob[17] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[20], &_iob[18] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[21], &_iob[19] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[22], &_iob[20] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[23], &_iob[21] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[24], &_iob[22] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[25], &_iob[23] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[26], &_iob[24] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[27], &_iob[25] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[28], &_iob[26] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[29], &_iob[27] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[30], &_iob[28] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[31], &_iob[29] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[32], &_iob[30] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[33], &_iob[31] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[34], &_iob[32] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[35], &_iob[33] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[36], &_iob[34] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[37], &_iob[35] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[38], &_iob[36] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[39], &_iob[37] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[40], &_iob[38] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[41], &_iob[39] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[42], &_iob[40] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[43], &_iob[41] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[44], &_iob[42] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[45], &_iob[43] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[46], &_iob[44] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[47], &_iob[45] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[48], &_iob[46] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[49], &_iob[47] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[50], &_iob[48] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[51], &_iob[49] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[52], &_iob[50] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[53], &_iob[51] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[54], &_iob[52] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[55], &_iob[53] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[56], &_iob[54] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[57], &_iob[55] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[58], &_iob[56] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[59], &_iob[57] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[60], &_iob[58] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[61], &_iob[59] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[62], &_iob[60] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, &_iob[63], &_iob[61] }, 
		{ 0, NULL, NULL, _IOIOB, 0, NULL, NULL, &_iob[62] } 
	};
FILE *_firstbuf = _iob;
FILE *_freeiob = &_iob[ 3 ];
FILE *_freemalloc = NULL;
#endif /* DYNAMIC */
